# Generated by Django 5.0.7 on 2024-08-12 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('video_title', models.CharField(max_length=1000)),
                ('video_description', models.TextField()),
                ('video_channel', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='video_channel',
        ),
        migrations.RemoveField(
            model_name='note',
            name='video_description',
        ),
        migrations.RemoveField(
            model_name='note',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='video_title',
        ),
        migrations.AddField(
            model_name='note',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Note.video_detail'),
        ),
    ]
