# Generated by Django 5.0.7 on 2024-08-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0002_video_detail_remove_note_video_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
